### ISSUE TITLE
Color coded freq option

### ISSUE THREAD

**Issue by Rescue9** [df8oe/UHSDR#15]
As a new General Class holder, it would be nice to have two additional options in the menu.

1) Option to color code frequency based upon license class when frequency goes outside class privileges. {Off, Orange Yellow, etc.}
2) Option to select current license class.

This way, those of us who are new and are learning on our mcHF would have less chance to violate our c!ass privileges. I also believe this is mod necessary due to the portable nature of the radio and the small likelihood that one would have a band plan, or additional documentation, handy for reference.

**Comment by Rescue9** [comment]
Issue in wrong repo. Closing.

**Comment by df8oe** [comment]
Very good idea. It can be paired with known CW / RTTY WSPR and so on spans and be coloured differently. Also transmitting can be disabled if you leave the span where you do have license (overrideable). Table can be added via USB-memory-key in txt form. I will think about this...

vy 73
Andreas
